make main ../../../PintFiles/model.an
make main ../../../PintFiles/apoptosis_stable.an
make main ../../../PintFiles/g2a.an
make main ../../../PintFiles/g2a_with_names.an
make main ../../../PintFiles/[v102]__[r157]__[INTERFERON-1]__[covid-uni-lu].an
make main ../../../PintFiles/[v104]__[r166]__[ETC]__[covid-uni-lu].an
make main ../../../PintFiles/[v104]__[r226]__[EGFR-ERBB-SIGNALING]__[cellcollective].an
make main ../../../PintFiles/[v10]__[r14]__[AP-1-ELSE-0-WT]__[ginsim].an
make main ../../../PintFiles/[v10]__[r18]__[ROOT-STEM-CELL-NICHE]__[biomodels].an
make main ../../../PintFiles/[v10]__[r27]__[FISSION-YEAST-DAVIDICH-2008]__[ginsim].an
make main ../../../PintFiles/[v10]__[r34]__[BOOLEAN-CELL-CYCLE]__[ginsim].an
make main ../../../PintFiles/[v10]__[r35]__[MAMMALIAN-CELL-CYCLE]__[cellcollective].an
make main ../../../PintFiles/[v110]__[r212]__[RODRIGUEZ-JORGE-TCR-SIGNALLING-17-07-2018]__[ginsim].an
make main ../../../PintFiles/[v118]__[r218]__[IL1-SIGNALING]__[cellcollective].an
make main ../../../PintFiles/[v11]__[r11]__[TOLL-PATHWAY-12-06-2013]__[ginsim].an
make main ../../../PintFiles/[v11]__[r11]__[TOLL-PATHWAY-OF-DROSOPHILA]__[cellcollective].an
make main ../../../PintFiles/[v120]__[r195]__[COAGULATION-PATHWAY]__[covid-uni-lu].an
make main ../../../PintFiles/[v12]__[r30]__[METABOLIC-INTERACTIONS-IN-THE-GUT-MICROBIOME]__[cellcollective].an
make main ../../../PintFiles/[v131]__[r302]__[INFLUENZA-VIRUS-REPLICATION-CYCLE]__[cellcollective].an
make main ../../../PintFiles/[v139]__[r557]__[SIGNAL-TRANSDUCTION-IN-FIBROBLASTS]__[cellcollective].an
make main ../../../PintFiles/[v13]__[r18]__[REGULATION-OF-THE-LARABINOSE-OPERON]__[cellcollective].an
make main ../../../PintFiles/[v13]__[r22]__[LAC-OPERON]__[cellcollective].an
make main ../../../PintFiles/[v14]__[r66]__[ARABIDOPSIS-THALIANA-CELL-CYCLE]__[cellcollective].an
make main ../../../PintFiles/[v15]__[r38]__[CARDIAC-DEVELOPMENT]__[cellcollective].an
make main ../../../PintFiles/[v15]__[r38]__[PREDICTING-VARIABLES-IN-CARDIAC-GENE]__[cellcollective].an
make main ../../../PintFiles/[v15]__[r66]__[FANCONI-ANEMIA-AND-CHECKPOINT-RECOVERY]__[cellcollective].an
make main ../../../PintFiles/[v165]__[r275]__[VIRUS-REPLICATION-CYCLE]__[covid-uni-lu].an
make main ../../../PintFiles/[v168]__[r243]__[HMOX1-PATHWAY]__[covid-uni-lu].an
make main ../../../PintFiles/[v16]__[r22]__[NEUROTRANSMITTER-SIGNALING-PATHWAY]__[cellcollective].an
make main ../../../PintFiles/[v16]__[r41]__[SKBR3-BREAST-CELL-LINE]__[cellcollective].an
make main ../../../PintFiles/[v16]__[r46]__[BT474-BREAST-CELL-LINE]__[cellcollective].an
make main ../../../PintFiles/[v16]__[r46]__[HCC1954-BREAST-CELL-LINE]__[cellcollective].an
make main ../../../PintFiles/[v16]__[r58]__[MAPK-RED3-19-06-2013]__[ginsim].an
make main ../../../PintFiles/[v17]__[r29]__[DROSOPHILA-BODY-SEGMENTATION]__[cellcollective].an
make main ../../../PintFiles/[v17]__[r78]__[MAPK-RED1-19-06-2013]__[ginsim].an
make main ../../../PintFiles/[v188]__[r351]__[CD4-T-CELL-SIGNALING]__[cellcollective].an
make main ../../../PintFiles/[v18]__[r18]__[VEGF-PATHWAY-12-06-2013]__[ginsim].an
make main ../../../PintFiles/[v18]__[r18]__[VEGF-PATHWAY-OF-DROSOPHILA]__[cellcollective].an
make main ../../../PintFiles/[v18]__[r43]__[TLGL-SURVIVAL-NETWORK]__[cellcollective].an
make main ../../../PintFiles/[v18]__[r58]__[BUDDING-YEAST-IRONS-2009]__[ginsim].an
make main ../../../PintFiles/[v18]__[r59]__[BUDDING-YEAST-CELL-CYCLE]__[cellcollective].an
make main ../../../PintFiles/[v18]__[r60]__[MAPK-RED2-12-06-2013]__[ginsim].an
make main ../../../PintFiles/[v18]__[r78]__[CD4-T-CELL-DIFFERENTIATION]__[cellcollective].an
make main ../../../PintFiles/[v18]__[r83]__[T-CD4-LYMPHOCYTE-TRANSCRIPTION]__[biomodels].an
make main ../../../PintFiles/[v193]__[r328]__[KYNURENINE-PATHWAY]__[covid-uni-lu].an
make main ../../../PintFiles/[v19]__[r21]__[JNK-PATHWAY]__[covid-uni-lu].an
make main ../../../PintFiles/[v19]__[r32]__[OXIDATIVE-STRESS-PATHWAY]__[cellcollective].an
make main ../../../PintFiles/[v19]__[r73]__[INFLAMMATORY-RESPONSES]__[biomodels].an
make main ../../../PintFiles/[v19]__[r79]__[HUMAN-GONADAL-SEX-DETERMINATION]__[cellcollective].an
make main ../../../PintFiles/[v205]__[r269]__[ER-STRESS]__[covid-uni-lu].an
make main ../../../PintFiles/[v20]__[r48]__[ERB-B2]__[ginsim].an
make main ../../../PintFiles/[v20]__[r51]__[MAMMALIAN-CELL-CYCLE-1607]__[cellcollective].an
make main ../../../PintFiles/[v20]__[r88]__[SUPP-MAT-MOD-NET]__[ginsim].an
make main ../../../PintFiles/[v21]__[r24]__[TGFB-pathway]__[covid-uni-lu].an
make main ../../../PintFiles/[v22]__[r39]__[B-CELL-DIFFERENTIATION]__[cellcollective].an
make main ../../../PintFiles/[v23]__[r24]__[FGF-PATHWAY-12-06-2013]__[ginsim].an
make main ../../../PintFiles/[v23]__[r24]__[FGF-PATHWAY-OF-DROSOPHILA]__[cellcollective].an
make main ../../../PintFiles/[v23]__[r34]__[T-CELL-DIFFERENTIATION]__[cellcollective].an
make main ../../../PintFiles/[v23]__[r43]__[AURORA-KINASE-A-IN-NEUROBLASTOMA]__[cellcollective].an
make main ../../../PintFiles/[v247]__[r1100]__[ERBB-14-RECEPTOR-SIGNALING]__[cellcollective].an
make main ../../../PintFiles/[v24]__[r28]__[PROCESSING-OF-SPZ-NETWORK-FROM-DROSOPHILA]__[cellcollective].an
make main ../../../PintFiles/[v24]__[r28]__[SPZ-PROCESSING-12-06-2013]__[ginsim].an
make main ../../../PintFiles/[v24]__[r32]__[HH-PATHWAY-11-06-2013]__[ginsim].an
make main ../../../PintFiles/[v24]__[r32]__[HH-PATHWAY-OF-DROSOPHILA]__[cellcollective].an
make main ../../../PintFiles/[v24]__[r48]__[TOL-REGULATORY-NETWORK]__[cellcollective].an
make main ../../../PintFiles/[v25]__[r67]__[S-PHASE-ENTRY-SIGNALLING-PATHWAY]__[biomodels].an
make main ../../../PintFiles/[v25]__[r70]__[BT474-BREAST-CELL-LINE-LONGTERM]__[cellcollective].an
make main ../../../PintFiles/[v25]__[r70]__[HCC1954-BREAST-CELL-LINE-LONGTERM]__[cellcollective].an
make main ../../../PintFiles/[v25]__[r81]__[SKBR3-BREAST-CELL-LINE-LONGTERM]__[cellcollective].an
make main ../../../PintFiles/[v260]__[r258]__[NSP9-PROTEIN]__[covid-uni-lu].an
make main ../../../PintFiles/[v26]__[r28]__[WG-PATHWAY-11-06-2013]__[ginsim].an
make main ../../../PintFiles/[v26]__[r29]__[WG-PATHWAY-OF-DROSOPHILA]__[cellcollective].an
make main ../../../PintFiles/[v26]__[r58]__[TRICHOSTRONGYLUS-RETORTAEFORMIS]__[cellcollective].an
make main ../../../PintFiles/[v26]__[r79]__[HSPC-MSC-0]__[ginsim].an
make main ../../../PintFiles/[v26]__[r81]__[PROINFLAMMATORY-TUMOR-MICROENVIRONMENT]__[cellcollective].an
make main ../../../PintFiles/[v28]__[r123]__[FA-BRCA-PATHWAY]__[cellcollective].an
make main ../../../PintFiles/[v28]__[r45]__[CALZONE-CELL-FATE]__[ginsim].an
make main ../../../PintFiles/[v28]__[r45]__[DEATH-RECEPTOR-SIGNALING]__[cellcollective].an
make main ../../../PintFiles/[v29]__[r128]__[BLOOD-STEM-CELL-NETWORK]__[biomodels].an
make main ../../../PintFiles/[v31]__[r36]__[APOPTOSIS]__[covid-uni-lu].an
make main ../../../PintFiles/[v31]__[r50]__[SEPARATION-INITIATION-NETWORK]__[cellcollective].an
make main ../../../PintFiles/[v321]__[r533]__[SIGNALING-IN-MACROPHAGE-ACTIVATION]__[cellcollective].an
make main ../../../PintFiles/[v32]__[r156]__[TUMOR-CELL-INVASION-AND-MIGRATION]__[cellcollective].an
make main ../../../PintFiles/[v33]__[r52]__[CELL-FATE-MULTISCALE]__[ginsim].an
make main ../../../PintFiles/[v33]__[r79]__[BORDETELLA-BRONCHISEPTICA]__[cellcollective].an
make main ../../../PintFiles/[v33]__[r94]__[LYMPHOID-AND-MYELOID-CELL-SPECIFICATION]__[cellcollective].an
make main ../../../PintFiles/[v34]__[r40]__[RTC-AND-TRANSCRIPTION]__[covid-uni-lu].an
make main ../../../PintFiles/[v34]__[r43]__[CHOLESTEROL-REGULATORY-PATHWAY]__[cellcollective].an
make main ../../../PintFiles/[v351]__[r737]__[NSP14]__[covid-uni-lu].an
make main ../../../PintFiles/[v38]__[r38]__[E-PROTEIN]__[covid-uni-lu].an
make main ../../../PintFiles/[v38]__[r96]__[CD4-T-CELL-DIFFERENTIATION-6678]__[cellcollective].an
make main ../../../PintFiles/[v40]__[r53]__[T-CELL-SIGNALING]__[cellcollective].an
make main ../../../PintFiles/[v40]__[r57]__[TCR-SIG-40]__[ginsim].an
make main ../../../PintFiles/[v41]__[r73]__[APOPTOSIS-NETWORK]__[cellcollective].an
make main ../../../PintFiles/[v42]__[r51]__[TREATMENT-OF-PROSTATE-CANCER]__[cellcollective].an
make main ../../../PintFiles/[v44]__[r78]__[GUARD-CELL-ABSCISIC-ACID-SIGNALING]__[cellcollective].an
make main ../../../PintFiles/[v47]__[r49]__[ORF3A]__[covid-uni-lu].an
make main ../../../PintFiles/[v48]__[r52]__[IFN-LAMBDA]__[covid-uni-lu].an
make main ../../../PintFiles/[v49]__[r167]__[STOMATAL-OPENING]__[cellcollective].an
make main ../../../PintFiles/[v50]__[r97]__[DIFFERENTIATION-OF-T-LYMPHOCYTES]__[cellcollective].an
make main ../../../PintFiles/[v51]__[r96]__[SENESCENCE-ASSOCIATED-SECRETORY-PHENOTYPE]__[cellcollective].an
make main ../../../PintFiles/[v52]__[r92]__[ORF10-CUL2-PATHWAY]__[covid-uni-lu].an
make main ../../../PintFiles/[v53]__[r104]__[MAPK-CANCER-CELL-FATE]__[cellcollective].an
make main ../../../PintFiles/[v53]__[r104]__[MAPK-LARGE-19-06-2013]__[ginsim].an
make main ../../../PintFiles/[v53]__[r135]__[B-BRONCHISEPTICA-AND-T-RETORTAEFORMIS]__[cellcollective].an
make main ../../../PintFiles/[v5]__[r14]__[CORTICAL-AREA-DEVELOPMENT]__[cellcollective].an
make main ../../../PintFiles/[v5]__[r15]__[G2A]__[ginsim].an
make main ../../../PintFiles/[v60]__[r193]__[T-LGL]__[ginsim].an
make main ../../../PintFiles/[v60]__[r195]__[TLGL-SURVIVAL-NETWORK-2011]__[cellcollective].an
make main ../../../PintFiles/[v60]__[r62]__[NSP4-NSP6]__[covid-uni-lu].an
make main ../../../PintFiles/[v61]__[r193]__[TLGL-SURVIVAL-NETWORK-2008]__[cellcollective].an
make main ../../../PintFiles/[v62]__[r108]__[PC12-CELL-DIFFERENTIATION]__[cellcollective].an
make main ../../../PintFiles/[v66]__[r128]__[IMMUNE-CHECKPOINT-NETWORK]__[DOI-10.3390-cancers12123600].an
make main ../../../PintFiles/[v66]__[r139]__[SIGNALING-PATHWAY-FOR-BUTHANOL-PRODUCTION]__[cellcollective].an
make main ../../../PintFiles/[v67]__[r131]__[BORTEZOMIB-RESPONSES-IN-U266]__[cellcollective].an
make main ../../../PintFiles/[v68]__[r103]__[HGF-SIGNALING-IN-KERATINOCYTES]__[cellcollective].an
make main ../../../PintFiles/[v6]__[r11]__[ZEBRA-MIR9-22-07-2011]__[ginsim].an
make main ../../../PintFiles/[v70]__[r153]__[COLITISASSOCIATE-COLON-CANCER]__[cellcollective].an
make main ../../../PintFiles/[v73]__[r114]__[YEAST-APOPTOSIS]__[cellcollective].an
make main ../../../PintFiles/[v73]__[r97]__[GLUCOSE-REPRESSION-SIGNALING-2009]__[cellcollective].an
make main ../../../PintFiles/[v81]__[r160]__[LIMPHOPOIESIS-REGULATORY-NETWORK]__[cellcollective].an
make main ../../../PintFiles/[v85]__[r130]__[RENIN-ANGIOTENSIN]__[covid-uni-lu].an
make main ../../../PintFiles/[v86]__[r149]__[IL6-SIGNALING]__[cellcollective].an
make main ../../../PintFiles/[v91]__[r104]__[PAMP-SIGNALING]__[covid-uni-lu].an
make main ../../../PintFiles/[v94]__[r132]__[PYRIMIDINE-DEPRIVATION]__[covid-uni-lu].an
make main ../../../PintFiles/[v9]__[r12]__[G2B]__[ginsim].an
make main ../../../PintFiles/[v9]__[r19]__[BUDDING-YEAST-ORLANDO-2008]__[ginsim].an
make main ../../../PintFiles/[v9]__[r19]__[CELL-CYCLE-TRANSCRIPTION]__[cellcollective].an