timeout --foreground 400 ./main ../../../PintFiles/model.an
timeout --foreground 400 ./main ../../../PintFiles/apoptosis_stable.an
timeout --foreground 400 ./main ../../../PintFiles/g2a.an
timeout --foreground 400 ./main ../../../PintFiles/g2a_with_names.an
timeout --foreground 400 ./main ../../../PintFiles/[v10]__[r14]__[AP-1-ELSE-0-WT]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v10]__[r18]__[ROOT-STEM-CELL-NICHE]__[biomodels].an
timeout --foreground 400 ./main ../../../PintFiles/[v10]__[r27]__[FISSION-YEAST-DAVIDICH-2008]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v10]__[r34]__[BOOLEAN-CELL-CYCLE]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v10]__[r35]__[MAMMALIAN-CELL-CYCLE]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v11]__[r11]__[TOLL-PATHWAY-12-06-2013]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v11]__[r11]__[TOLL-PATHWAY-OF-DROSOPHILA]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v12]__[r30]__[METABOLIC-INTERACTIONS-IN-THE-GUT-MICROBIOME]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v13]__[r18]__[REGULATION-OF-THE-LARABINOSE-OPERON]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v13]__[r22]__[LAC-OPERON]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v14]__[r66]__[ARABIDOPSIS-THALIANA-CELL-CYCLE]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v15]__[r38]__[CARDIAC-DEVELOPMENT]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v15]__[r38]__[PREDICTING-VARIABLES-IN-CARDIAC-GENE]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v15]__[r66]__[FANCONI-ANEMIA-AND-CHECKPOINT-RECOVERY]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v16]__[r22]__[NEUROTRANSMITTER-SIGNALING-PATHWAY]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v16]__[r41]__[SKBR3-BREAST-CELL-LINE]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v16]__[r46]__[BT474-BREAST-CELL-LINE]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v16]__[r46]__[HCC1954-BREAST-CELL-LINE]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v16]__[r58]__[MAPK-RED3-19-06-2013]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v17]__[r29]__[DROSOPHILA-BODY-SEGMENTATION]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v17]__[r78]__[MAPK-RED1-19-06-2013]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v18]__[r18]__[VEGF-PATHWAY-12-06-2013]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v18]__[r18]__[VEGF-PATHWAY-OF-DROSOPHILA]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v18]__[r43]__[TLGL-SURVIVAL-NETWORK]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v18]__[r58]__[BUDDING-YEAST-IRONS-2009]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v18]__[r59]__[BUDDING-YEAST-CELL-CYCLE]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v18]__[r60]__[MAPK-RED2-12-06-2013]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v18]__[r78]__[CD4-T-CELL-DIFFERENTIATION]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v18]__[r83]__[T-CD4-LYMPHOCYTE-TRANSCRIPTION]__[biomodels].an
timeout --foreground 400 ./main ../../../PintFiles/[v19]__[r21]__[JNK-PATHWAY]__[covid-uni-lu].an
timeout --foreground 400 ./main ../../../PintFiles/[v19]__[r32]__[OXIDATIVE-STRESS-PATHWAY]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v19]__[r73]__[INFLAMMATORY-RESPONSES]__[biomodels].an
timeout --foreground 400 ./main ../../../PintFiles/[v19]__[r79]__[HUMAN-GONADAL-SEX-DETERMINATION]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v20]__[r48]__[ERB-B2]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v20]__[r51]__[MAMMALIAN-CELL-CYCLE-1607]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v20]__[r88]__[SUPP-MAT-MOD-NET]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v21]__[r24]__[TGFB-pathway]__[covid-uni-lu].an
timeout --foreground 400 ./main ../../../PintFiles/[v22]__[r39]__[B-CELL-DIFFERENTIATION]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v23]__[r24]__[FGF-PATHWAY-12-06-2013]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v23]__[r24]__[FGF-PATHWAY-OF-DROSOPHILA]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v23]__[r34]__[T-CELL-DIFFERENTIATION]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v23]__[r43]__[AURORA-KINASE-A-IN-NEUROBLASTOMA]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v24]__[r28]__[PROCESSING-OF-SPZ-NETWORK-FROM-DROSOPHILA]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v24]__[r28]__[SPZ-PROCESSING-12-06-2013]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v24]__[r32]__[HH-PATHWAY-11-06-2013]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v24]__[r32]__[HH-PATHWAY-OF-DROSOPHILA]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v24]__[r48]__[TOL-REGULATORY-NETWORK]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v25]__[r67]__[S-PHASE-ENTRY-SIGNALLING-PATHWAY]__[biomodels].an
timeout --foreground 400 ./main ../../../PintFiles/[v25]__[r70]__[BT474-BREAST-CELL-LINE-LONGTERM]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v25]__[r70]__[HCC1954-BREAST-CELL-LINE-LONGTERM]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v25]__[r81]__[SKBR3-BREAST-CELL-LINE-LONGTERM]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v26]__[r28]__[WG-PATHWAY-11-06-2013]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v26]__[r29]__[WG-PATHWAY-OF-DROSOPHILA]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v26]__[r58]__[TRICHOSTRONGYLUS-RETORTAEFORMIS]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v26]__[r79]__[HSPC-MSC-0]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v26]__[r81]__[PROINFLAMMATORY-TUMOR-MICROENVIRONMENT]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v28]__[r123]__[FA-BRCA-PATHWAY]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v28]__[r45]__[CALZONE-CELL-FATE]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v28]__[r45]__[DEATH-RECEPTOR-SIGNALING]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v29]__[r128]__[BLOOD-STEM-CELL-NETWORK]__[biomodels].an
timeout --foreground 400 ./main ../../../PintFiles/[v31]__[r36]__[APOPTOSIS]__[covid-uni-lu].an
timeout --foreground 400 ./main ../../../PintFiles/[v31]__[r50]__[SEPARATION-INITIATION-NETWORK]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v32]__[r156]__[TUMOR-CELL-INVASION-AND-MIGRATION]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v33]__[r52]__[CELL-FATE-MULTISCALE]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v33]__[r79]__[BORDETELLA-BRONCHISEPTICA]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v34]__[r40]__[RTC-AND-TRANSCRIPTION]__[covid-uni-lu].an
timeout --foreground 400 ./main ../../../PintFiles/[v34]__[r43]__[CHOLESTEROL-REGULATORY-PATHWAY]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v38]__[r38]__[E-PROTEIN]__[covid-uni-lu].an
timeout --foreground 400 ./main ../../../PintFiles/[v40]__[r57]__[TCR-SIG-40]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v5]__[r14]__[CORTICAL-AREA-DEVELOPMENT]__[cellcollective].an
timeout --foreground 400 ./main ../../../PintFiles/[v5]__[r15]__[G2A]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v6]__[r11]__[ZEBRA-MIR9-22-07-2011]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v9]__[r12]__[G2B]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v9]__[r19]__[BUDDING-YEAST-ORLANDO-2008]__[ginsim].an
timeout --foreground 400 ./main ../../../PintFiles/[v9]__[r19]__[CELL-CYCLE-TRANSCRIPTION]__[cellcollective].an